# Generated by Django 3.1.6 on 2021-02-12 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sibdevapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deals',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='sibdevapp.customer'),
        ),
    ]
